import {
  LOGIN_MUTATION,
  REGISTER_MUTATION,
  UPDATE_USER_MUTATION
} from './mutation/userMutation';

import {
  HOSPITAL_MUTATION,
  HOSPITAL_UPDATE_MUTATION
} from './mutation/hospitalMutation';

import {
  DOCTOR_LOGIN_MUTATION,
  DOCTOR_REGISTER_MUTATION,
  UPDATE_DOCTOR_MUTATION
} from './mutation/doctorMutation';

import { UPLOAD_FILE } from './mutation/uploadFileMutation';

export {
  LOGIN_MUTATION,
  REGISTER_MUTATION,
  UPDATE_USER_MUTATION,
  HOSPITAL_MUTATION,
  HOSPITAL_UPDATE_MUTATION,
  UPLOAD_FILE,
  DOCTOR_LOGIN_MUTATION,
  DOCTOR_REGISTER_MUTATION,
  UPDATE_DOCTOR_MUTATION
};



