import {
  LOGIN_MUTATION,
  REGISTER_MUTATION,
  UPDATE_USER_MUTATION,
  REMOVE_USER_MUTATION,
} from './mutation/userMutation';

import {
  HOSPITAL_MUTATION,
  HOSPITAL_UPDATE_MUTATION
} from './mutation/hospitalMutation';

import { UPLOAD_FILE } from './mutation/uploadFileMutation';

export {
  LOGIN_MUTATION,
  REGISTER_MUTATION,
  UPDATE_USER_MUTATION,
  HOSPITAL_MUTATION,
  HOSPITAL_UPDATE_MUTATION,
  UPLOAD_FILE,
  REMOVE_USER_MUTATION
};



